name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: install dependencies
        run: npm install

      - name: run markdownlint
        run: make markdownlint

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: install dependencies
        run: npm install

      - name: run markdown-link-check
        run: make markdown-link-check

  markdown-toc-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

    - name: install dependencies
      run: npm install

    - name: run markdown-toc
      run: make markdown-toc

    - name: validate markdown-toc
      run: git diff --exit-code ':*.md' || (echo 'Generated markdown Table of Contents is out of date, please run "make markdown-toc" and commit the changes in this PR.' && exit 1)

  gen-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - run: make docker-pull
      - run: make gen-proto